apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-kibana-user-sa
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: logging
  name: create-kibana-user-role
rules:
- apiGroups: [""] # Permisos para crear el secret de Kibana
  resources: ["secrets"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-kibana-user-binding
  namespace: logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-kibana-user-role
subjects:
- kind: ServiceAccount
  name: create-kibana-user-sa
  namespace: logging