apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      volumes:
      - name: elasticsearch-ca
        secret:
          secretName: elasticsearch-ca
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.5.0
        ports:
        - containerPort: 5601
        env:
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: ELASTICSEARCH_HOSTS
          value: "https://elasticsearch.logging.svc.cluster.local:9200"
        - name: ELASTICSEARCH_USERNAME
          value: "kibana_system_user"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kibana-credentials # Creado por el Job
              key: password
        - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
          value: "full"
        - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
          value: "/usr/share/kibana/config/certs/ca.crt"
        volumeMounts:
        - name: elasticsearch-ca
          mountPath: /usr/share/kibana/config/certs
          readOnly: true