apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: logging
  name: elasticsearch-secret-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elasticsearch-secret-manager-binding
  namespace: logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: elasticsearch-secret-manager
subjects:
- kind: ServiceAccount
  name: elasticsearch
  namespace: logging